// make a small program that asks for a username and token through UI, the TOKEN is generated by getting the username, flipping it around
// if the user enters the correct token, the program will print "Access Granted", otherwise it will print "Access Denied", 
// the program will keep asking for the username and token until the user enters the correct token

#include <iostream>
#include <string>
#include <algorithm>

int main() {
    std::string username;
    std::string token;
    std::string correctToken;
    std::string cc;
    bool accessGranted = false;

    std::cout << "Enter your username: ";
    std::cin >> username;

    correctToken = username;
    std::reverse(correctToken.begin(), correctToken.end());

    while (!accessGranted) {
        std::cout << "Enter your token: ";
        std::cin >> token;

        if (token == correctToken) {
            std::cout << "Access Granted" << std::endl;
            accessGranted = true;
            std::cin >> cc;
        } else {
            std::cout << "Access Denied" << std::endl;
        }
    }

    return 0;
}